import 'address_model.dart';
import 'order_item_model.dart';
import 'payment_model.dart';

class OrderModel {
  final String? orderId; // Usually generated by backend
  final AddressModel shippingAddress;
  final PaymentModel paymentMethod;
  final List<OrderItemModel> items;
  final double subtotal;
  final double shippingFee;
  final double totalAmount;
  final DateTime createdAt;

  OrderModel({
    this.orderId,
    required this.shippingAddress,
    required this.paymentMethod,
    required this.items,
    required this.subtotal,
    required this.shippingFee,
    required this.totalAmount,
    required this.createdAt,
  });

  Map<String, dynamic> toJson() {
    return {
      'orderId': orderId,
      'shippingAddress': shippingAddress.toJson(),
      'paymentMethod': paymentMethod.toJson(),
      'items': items.map((item) => item.toJson()).toList(),
      'subtotal': subtotal,
      'shippingFee': shippingFee,
      'totalAmount': totalAmount,
      'createdAt': createdAt.toIso8601String(),
    };
  }
}
